api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import ExternalAPIClientView
from .views import StudentViewSet, ProfessorViewSet

router = DefaultRouter()
router.register(r'student', StudentViewSet)
router.register(r'professor', ProfessorViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('github/', ExternalAPIClientView.as_view())
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('pybo/', include('pybo.urls')),
]

pybo/urls.py
from django.urls import path

from . import views

#alias 중복 방지를 위한 별칭 지정
app_name = 'pybo'

urlpatterns = [
    # name값은 별칭(alias) 지정. 즉, pybo/는 index라는 이름, pybo/int/는 detail이라는 이름.
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
]

api/models.py
from django.db import models


class Professor(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    subject = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Student(models.Model):
    professor = models.ForeignKey(Professor, on_delete=models.CASCADE, null=False, blank=False, related_name='students')
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    def __str__(self):
        return self.name

pybo/models.py
from django.db import models

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

api/views.py
import json

import requests
from django.db import transaction
from django.shortcuts import get_object_or_404
from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import Professor, Student
from .serializers import ProfessorSerializer, StudentSerializer


class ProfessorViewSet(viewsets.ModelViewSet):
    queryset = Professor.objects.all()
    serializer_class = ProfessorSerializer

    @action(detail=False, methods=['GET'], url_path='students_by_professor_name')
    def students_by_professor_name(self, request):
        professor_name = request.query_params.get('name')
        if not professor_name:
            return Response({"error" : "name parameter is not included"}, status.HTTP_404_NOT_FOUND)
        professor = get_object_or_404(Professor, name=professor_name)
        students = professor.students.all()
        serializer = StudentSerializer(students, many=True)
        return Response(serializer.data)

    @action(detail=True, methods=['PATCH'], url_path='modify_professor_age')
    @transaction.atomic
    def modify_professor_age(self, request, pk=None):
        professor = get_object_or_404(self.get_queryset(), id=pk)
        professor.age = request.data.get('age')
        professor.save()
        serializer = ProfessorSerializer(professor)
        return Response(serializer.data, status.HTTP_202_ACCEPTED)

    @action(detail=False, methods=['POST'], url_path='delete_professor_name')
    @transaction.atomic
    def delete_professor_name(self, request):
        name = request.data.get('name')
        print(name)
        if not name:
            return Response({"error": "Name parameter is required."}, status=status.HTTP_400_BAD_REQUEST)
        professor = self.get_queryset().filter(name=name)
        print(professor)
        professor.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

    @action(detail=False, methods=['DELETE'], url_path='delete_professors_by_age')
    @transaction.atomic
    def delete_professors_by_age(self, request):
        age = request.data.get('age')
        if not age:
            return Response({"error": "Age parameter is required."}, status=status.HTTP_400_BAD_REQUEST)
        professors = self.get_queryset().filter(age=age)
        deleted_count = professors.delete()[0]
        return Response({"deleted_count": deleted_count}, status=status.HTTP_204_NO_CONTENT)

class StudentViewSet(viewsets.ModelViewSet):
    queryset = Student.objects.all()
    serializer_class = StudentSerializer

class ExternalAPIClientView(APIView):
    def get(self, request):
        external_url = "https://api.github.com/users/ambition-kwon"
        response = requests.get(external_url)
        print(json.dumps(response.text, indent=4))
        return Response(response.json())

pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .models import Question, Answer


def index(request):
    question_list = Question.objects.all().order_by('-created_at')
    context = {
        'question_list': question_list
    }
    # render 로 넘길 때는 무조건 dictionary 객체 여야함
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {
        "question": question,
    }
    return render(request, "pybo/question_detail.html", context)

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    answer = Answer(question=question, content=request.POST.get('content'))
    answer.save()
    return redirect('pybo:detail', question_id=question_id)

def question_create(request):
    subject = request.POST.get('subject')
    content = request.POST.get('content')
    question = Question(subject=subject, content=content)
    question.save()
    return redirect('pybo:index')

templates/pybo/question_detail.html
{% load static %}
<link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
{% if question.subject %}
    <h1>제목 : {{ question.subject }}</h1>
    <h3>내용</h3>
    <p>{{ question.content }}</p>
    <h5>생성시각 : {{ question.created_at }}</h5>
    <h5>등록된 답변 리스트({{ question.answers.count }}개)</h5>
    <ul>
        {% for answer in question.answers.all %}
        	<li>{{ answer.content }}</li>
        {% endfor %}
    </ul>
{% endif %}

<form action="{% url 'pybo:answer_create' question.id  %}" method="post">
    {% csrf_token %} {# 실제로 웹 브라우저에서 작성된 form인지 확인하는 보안관련 코드 #}
    <textarea name="content" id="content" rows="15"></textarea>
    <br>
    <input type="submit" value="답변 등록">
</form>

templates/pybo/question_list.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
{% load static %}
<link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
<h1>질문 리스트</h1>
{% if question_list %}
    <ul>
        {% for question in question_list %}
            <li><a href="{% url 'pybo:detail' question.pk %}">{{ question.subject }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h1>등록된 질문이 없습니다.</h1>
{% endif %}
<form action="{% url 'pybo:question_create' %}" method="post">
    {% csrf_token %} {# 실제로 웹 브라우저에서 작성된 form인지 확인하는 보안관련 코드 #}
    <h3>질문 제목</h3>
    <textarea name="subject" id="subject" rows="15"></textarea>
    <br>
    <h3>질문 내용</h3>
    <textarea name="content" id="content" rows="15"></textarea>
    <input type="submit" value="질문 등록">
</form>
</body>
</html>